$ErrorActionPreference = 'Stop'

function RemoveStringPrefix {
    Param ([String] $String, [String] $Prefix)
    if (!$String.StartsWith($Prefix)) { return $String; }
    return $String.Substring($Prefix.Length);
}

$GitString = RemoveStringPrefix (git describe --dirty --broken --match 'flexasio-*') 'flexasio-'

&{
    Write-Output '// FILE AUTOGENERATED BY version.ps1'
    Write-Output "#define FLEXASIO_VERSION ""$($GitString)"""
    Write-Output "#define FLEXASIO_BUILD_TIMESTR ""$(Get-Date -Format o)"""
} |
# Powershell by default outputs UTF-16, which confuses Inno Setup Preprocessor.
# If we use UTF-8, it still insists in outputting a BOM, which still confuses ISPP.
Out-File -Encoding ASCII ..\build\version.h
