$ErrorActionPreference = 'Stop'

function RemoveStringPrefix {
    Param ([String] $String, [String] $Prefix)
    if (!$String.StartsWith($Prefix)) { return $String; }
    return $String.Substring($Prefix.Length);
}

$GitString = RemoveStringPrefix (git describe --dirty --broken --match 'flexasio-*') 'flexasio-'

&{
    Write-Output '// FILE AUTOGENERATED BY version.ps1'
    Write-Output "#define FLEXASIO_VERSION ""$($GitString)"""
    Write-Output "#define FLEXASIO_BUILD_TIMESTR ""$(Get-Date -Format o)"""
} > ..\build\version.h
