[uuid(DCF8D18D-F399-49C8-8286-E84CA8AD7729)]
library audiolysAPODll
{
	[object, uuid(1C653355-6D85-43AD-9674-05D4549F19C1)]
	interface IFlexASIO : IUnknown
	{
	};

	[uuid(462F2ABF-5278-436A-95B6-72CBF65482AE)]
	coclass CFlexASIO
	{
		[default] interface IFlexASIO;
	};
}
