string(TIMESTAMP FLEXASIO_BUILD_TIMESTR UTC)
if (Git_FOUND)
	execute_process(
		COMMAND "${GIT_EXECUTABLE}" -C "${CMAKE_CURRENT_LIST_DIR}" describe
		OUTPUT_VARIABLE FLEXASIO_GIT_DESCRIPTION OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	execute_process(
		COMMAND "${GIT_EXECUTABLE}" -C "${CMAKE_CURRENT_LIST_DIR}" describe --dirty --broken --match "flexasio-*"
		OUTPUT_VARIABLE FLEXASIO_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	string(REGEX REPLACE "^flexasio-" "" FLEXASIO_VERSION "${FLEXASIO_VERSION}")
else()
	set(FLEXASIO_GIT_DESCRIPTION "unknown")
	set(FLEXASIO_VERSION "unknown")
endif()
