string(TIMESTAMP FLEXASIO_BUILD_TIMESTR UTC)
if (Git_FOUND)
	execute_process(
		COMMAND "${GIT_EXECUTABLE}" -C "${CMAKE_CURRENT_LIST_DIR}" describe
		OUTPUT_VARIABLE FLEXASIO_GIT_DESCRIPTION OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	execute_process(
		COMMAND "${GIT_EXECUTABLE}" -C "${CMAKE_CURRENT_LIST_DIR}" describe --dirty --broken
		OUTPUT_VARIABLE FLEXASIO_GIT_DESCRIPTION_DIRTY OUTPUT_STRIP_TRAILING_WHITESPACE
	)
else()
	set(FLEXASIO_GIT_DESCRIPTION "unknown")
	set(FLEXASIO_GIT_DESCRIPTION_DIRTY "unknown")
endif()
