string(TIMESTAMP FLEXASIO_BUILD_TIMESTR UTC)
if (Git_FOUND)
	execute_process(
		COMMAND "${GIT_EXECUTABLE}" -C "${CMAKE_CURRENT_LIST_DIR}" describe
		OUTPUT_VARIABLE FLEXASIO_GITSTR OUTPUT_STRIP_TRAILING_WHITESPACE
	)
else()
	set(FLEXASIO_GITSTR "unknown")
endif()
configure_file("${CMAKE_CURRENT_LIST_DIR}/version.in.h" "${OUTPUT_HEADER_FILE}" @ONLY ESCAPE_QUOTES)
